### ISSUE TITLE
VS1053 initialisation error

### ISSUE THREAD

**Issue by DSangyy** [yellobyte/ESP32-Webradio-PlusDLNA#2]
Awsome project you have, i am using it for my mini music client.
I've stumbled upon a problem, ENABLE_DIGITAL_INPUTS must be enabled for VS1053 to work, else it will raise "VS1053 not properly installed". I use pin 27, 14, 26 for cs, dcs, dreq. Guess the problem is pin 26 could not be read properly.

**Comment by yellobyte** [comment]
Hi there, thanks for your reply. I appreciate that.
Having a look at the code I see in function readIOprefs() the value for dreq_pin is assigned a default value (in my case: 4) unless you specify otherwise in the config file via Webbrowser.
Then in setup() the VS1053 object is created and initialized with above chosen DREQ pin number:
...  
  vs1053player = new VS1053(ini_block.vs_cs_pin,        // Make instance of player
                            ini_block.vs_dcs_pin,
                            **ini_block.vs_dreq_pin,**      <------------- DREQ pin number 
                            ini_block.vs_shutdown_pin);
...  
A few lines further down is a function call to the VS1053 initialization routine:
...  
  **vs1053player->begin();**                               // initialize VS1053 player
...  
In this initialization routine the actual ESP32 port (DREQ should be connected to) gets initialized:
...  
void VS1053::begin()
{
  **pinMode(dreq_pin, INPUT);**                            // DREQ is an input         <------------- DREQ pin initialized
  pinMode(cs_pin, OUTPUT);                             // the SCI and SDI signals
...  
So without ENABLE_DIGITAL_INPUTS being defined the ESP32 DREQ port gets initialized properly in any case. Furthermore after an ESP32 reset all ports are set by default to mode INPUT anyway. 
From my point of view defining ENABLE_DIGITAL_INPUTS is not necessary for the VS1053 to work. My project runs ok this way.

You can try modifying above line to  "pinMode(dreq_pin, **INPUT_PULLUP**);" and see if it changes anything. That might suppress the error in case the VS1053 DREQ line is not properly connected to the ESP32 and you don't have a **pullup resistor** on that pin. However, without that connection it won't work later on. 
I hope I have understood your problem accurately, otherwise come back to me.
Regards Thomas

**Comment by DSangyy** [comment]
Thanks for your quick reply. The pin number was not the case, since i set all pin default values to -1 and let them get the respective values in nvs when boot up. I've tried to set the default dreq pin to 26 before, not working also. I will further test dreq with another gpio pin and see if it works.
By the way i'm trying to output and use i2s signal with another esp32 as an i2s-to-spdif converter. Will let you know the result.

**Comment by yellobyte** [comment]
An oscilloscope helped me a lot finding errors, wouldn't want to live without one. Let me know how it goes. Good luck.
BTW: If you like this project, please give it a star. Thanks. :-)
